### ISSUE TITLE
Inspección MB 🦖 

### ISSUE THREAD

**Issue by MaritzaB** [IslasGECI/metadata_tools#10]
`test_DataTable.py`

- [x] Poner todas las variables en inglés.

Línea 17: `nombre_capturas: str = "Capturas"`
-  talvez un mejor nombre podrías ser: `captures_column`?

Cambiar el orden de las variables de la prueba `def test_get_variable_name_from_standard_name():` para que siga la misma estética que la prueba `def test_get_value():` (o viceversa).
```
def test_get_variable_name_from_standard_name():
    expected_name: str = "Esfuerzo"
    obtained_name: str = DatosSocorro.get_variable_name_from_standard_name(mdt.StandardName.effort)
    assert expected_name == obtained_name


def test_get_value():
    nombre_capturas: str = "Capturas"
    obtained_catches: np.array = np.array(DatosSocorro.get_value(nombre_capturas))
    expected_catches: np.array = np.array([51, 31, 33, 21, 10])
    are_equal = (expected_catches == obtained_catches).all()
    assert are_equal
```
por
```
def test_get_variable_name_from_standard_name():
    obtained_name: str = DatosSocorro.get_variable_name_from_standard_name(mdt.StandardName.effort)
    expected_name: str = "Esfuerzo"
    assert expected_name == obtained_name


def test_get_value():
    nombre_capturas: str = "Capturas"
    obtained_catches: np.array = np.array(DatosSocorro.get_value(nombre_capturas))
    expected_catches: np.array = np.array([51, 31, 33, 21, 10])
    are_equal = (expected_catches == obtained_catches).all()
    assert are_equal
```

**Comment by MaritzaB** [comment]
`Tablanal`

¿Estamos usando lo que está dentro de la clase, ya que todos tienen `pass` ? ¿son métodos? 

```
class DataTable:
    def __init__(self):
        pass
    def readExcel(self, nombreArchivo):
        pass
    def getVariableNameFromAxis(self, nombreEje):
        pass 
```

**Comment by MaritzaB** [comment]
`DatpackageModifier`

El nombre talvez era `DatapackageModifier`

En el siguiente código, diccionario podría estar en inglés ` self._diccionario`? :
```
    def __init__(self, diccionario_datapackage):
        self._diccionario = copy.deepcopy(diccionario_datapackage)
        self._resources = [Resource(recurso) for recurso in self._diccionario["resources"]]
```

¿Nos conviene acompletar el nombre?:
`def resources(self)` --> `def get_resources(self)`
`def get_dict(self):` --> `def get_dictinonary(self):`

**Comment by MaritzaB** [comment]
`test_datapackage.py`

La prueba se llama `def test_Field_add_property()` pero la función se llama `def add_property()`.
¿Nos conviene que se la prueba se llame `def test_add_property`?

Lo mismo para `def test_Field_modify_property()` --> `def test_modify_property()`

**Comment by nepito** [comment]
> `Tablanal`
> 
> ¿Estamos usando lo que está dentro de la clase, ya que todos tienen `pass` ? ¿son métodos?
> 
> ```
> class DataTable:
>     def __init__(self):
>         pass
>     def readExcel(self, nombreArchivo):
>         pass
>     def getVariableNameFromAxis(self, nombreEje):
>         pass 
> ```

Ya borramos este archivo

**Comment by nepito** [comment]
> `test_datapackage.py`
> 
> La prueba se llama `def test_Field_add_property()` pero la función se llama `def add_property()`.
> ¿Nos conviene que se la prueba se llame `def test_add_property`?
> 
> Lo mismo para `def test_Field_modify_property()` --> `def test_modify_property()`

Aquí la parte `Field` hace referencia que estamos probando el método de la clase `Field`. La autora en [esta nota](https://blog.thea.codes/my-python-testing-style-guide/) sugieren que hagamos una clase para probar las clases. Algo similar a las pruebas en `unittest`. Esta es una alternativa a esa propuesta. 

Además, ya borramos la clase `Field` por lo que también borramos esa prueba.

**Comment by nepito** [comment]
> `test_DataTable.py`
> 
> * [ ]  Poner todas las variables en inglés.
> 
> Línea 17: `nombre_capturas: str = "Capturas"`
> 
> * talvez un mejor nombre podrías ser: `captures_column`?
> 
> Cambiar el orden de las variables de la prueba `def test_get_variable_name_from_standard_name():` para que siga la misma estética que la prueba `def test_get_value():` (o viceversa).
> 
> ```
> def test_get_variable_name_from_standard_name():
>     expected_name: str = "Esfuerzo"
>     obtained_name: str = DatosSocorro.get_variable_name_from_standard_name(mdt.StandardName.effort)
>     assert expected_name == obtained_name
> 
> 
> def test_get_value():
>     nombre_capturas: str = "Capturas"
>     obtained_catches: np.array = np.array(DatosSocorro.get_value(nombre_capturas))
>     expected_catches: np.array = np.array([51, 31, 33, 21, 10])
>     are_equal = (expected_catches == obtained_catches).all()
>     assert are_equal
> ```
> 
> por
> 
> ```
> def test_get_variable_name_from_standard_name():
>     obtained_name: str = DatosSocorro.get_variable_name_from_standard_name(mdt.StandardName.effort)
>     expected_name: str = "Esfuerzo"
>     assert expected_name == obtained_name
> 
> 
> def test_get_value():
>     nombre_capturas: str = "Capturas"
>     obtained_catches: np.array = np.array(DatosSocorro.get_value(nombre_capturas))
>     expected_catches: np.array = np.array([51, 31, 33, 21, 10])
>     are_equal = (expected_catches == obtained_catches).all()
>     assert are_equal
> ```

Atendí la segunda parte, en la que parecen las variables esperadas primera `expected_variable` en [esta consignación](https://github.com/IslasGECI/metadata_tools/pull/12/commits/b9760bce68644fd8c84b91948422739adf7751f8).

Creo que para atender esta corrección por completo deberemos cambiar también a inglés estas variables:
![image](https://user-images.githubusercontent.com/35377740/115084159-4cd58000-9ebd-11eb-8f1e-e0a8a05b06d1.png)

**Comment by nepito** [comment]
> > `test_DataTable.py`
> > 
> > * [x]   Poner todas las variables en inglés.
> > 
> > Línea 17: `nombre_capturas: str = "Capturas"`
> > 
> > * talvez un mejor nombre podrías ser: `captures_column`?
> > 
> > Cambiar el orden de las variables de la prueba `def test_get_variable_name_from_standard_name():` para que siga la misma estética que la prueba `def test_get_value():` (o viceversa).
> > ```
> > def test_get_variable_name_from_standard_name():
> >     expected_name: str = "Esfuerzo"
> >     obtained_name: str = DatosSocorro.get_variable_name_from_standard_name(mdt.StandardName.effort)
> >     assert expected_name == obtained_name
> > 
> > 
> > def test_get_value():
> >     nombre_capturas: str = "Capturas"
> >     obtained_catches: np.array = np.array(DatosSocorro.get_value(nombre_capturas))
> >     expected_catches: np.array = np.array([51, 31, 33, 21, 10])
> >     are_equal = (expected_catches == obtained_catches).all()
> >     assert are_equal
> > ```
> > 
> > 
> > por
> > ```
> > def test_get_variable_name_from_standard_name():
> >     obtained_name: str = DatosSocorro.get_variable_name_from_standard_name(mdt.StandardName.effort)
> >     expected_name: str = "Esfuerzo"
> >     assert expected_name == obtained_name
> > 
> > 
> > def test_get_value():
> >     nombre_capturas: str = "Capturas"
> >     obtained_catches: np.array = np.array(DatosSocorro.get_value(nombre_capturas))
> >     expected_catches: np.array = np.array([51, 31, 33, 21, 10])
> >     are_equal = (expected_catches == obtained_catches).all()
> >     assert are_equal
> > ```
> 
> Atendí la segunda parte, en la que parecen las variables esperadas primera `expected_variable` en [esta consignación](https://github.com/IslasGECI/metadata_tools/pull/12/commits/b9760bce68644fd8c84b91948422739adf7751f8).
> 
> Creo que para atender esta corrección por completo deberemos cambiar también a inglés estas variables:
> ![image](https://user-images.githubusercontent.com/35377740/115084159-4cd58000-9ebd-11eb-8f1e-e0a8a05b06d1.png)

Listo @MaritzaB ya cambié a inglés el nombre de las variables :raised_hands:

**Comment by nepito** [comment]
> `DatpackageModifier`
> 
> El nombre talvez era `DatapackageModifier`
> 
> En el siguiente código, diccionario podría estar en inglés ` self._diccionario`? :
> 
> ```
>     def __init__(self, diccionario_datapackage):
>         self._diccionario = copy.deepcopy(diccionario_datapackage)
>         self._resources = [Resource(recurso) for recurso in self._diccionario["resources"]]
> ```
> 
> ¿Nos conviene acompletar el nombre?:
> `def resources(self)` --> `def get_resources(self)`
> `def get_dict(self):` --> `def get_dictinonary(self):`

Ya no lo encuentro, seguro que también lo borramos :thinking:

**Comment by MaritzaB** [comment]
🔥 ⚰️ Un minuto de silencio por los archivos que ya no están más en este repo jajaja.
Súper @nepito, muchas gracias por resolverme las dudas del issue y por atender los comentarios 🙌🏽
