### ISSUE TITLE
Mutante con el id 2673

### ISSUE THREAD

**Issue by xwalls** [IslasGECI/metadata_tools#11]
En nuestro tomate, @islasfernando y yo intentamos cazar este mutante:

![image](https://user-images.githubusercontent.com/9456708/112536056-3b8bce80-8d6a-11eb-87a6-867e8226f5f8.png)

Hicimos una prueba pero no eliminó el mutante.
Tenemos la idea de refactorizar la función `where()`, extrayendo la parte del `copy.deep()` en un método aparte que después sea llamado por esta función `where()`

**Comment by nepito** [comment]
Make a deep copy, including a copy of the data and the indices. With deep=False neither the indices or the data are copied.

Note that when deep=True data is copied, actual python objects will not be copied recursively, only the reference to the object. This is in contrast to copy.deepcopy in the Standard Library, which recursively copies object data.

**Comment by evaristor** [comment]
@nepito @islasfernando @xwalls : 
¿Este _issue_ ya quedó resuelto?

**Comment by devarops** [comment]
@nepito @islasfernando @xwalls @MaritzaB : 
¿Este _issue_ ya quedó resuelto?

**Comment by nepito** [comment]
Ya quedó, le agregué el _pr_ con el que quedó, pero no se cerró en automático

**Comment by devarops** [comment]
@nepito: Creo que eso funciona solamente cuando agregas el PR **antes** de cerrarlo.
