### ISSUE TITLE
falta el archivo .gitignore

### ISSUE THREAD

**Issue by xwalls** [IslasGECI/metadata_tools#6]
en la mayoría de las carpetas se están generando archivos temporales, en su mayoría caches de python
al no haber un .gitignore estos pueden ser consignados por accidente. 

_Originally posted by @xwalls in https://github.com/IslasGECI/metadata_tools/issues/2#issuecomment-791031910_

**Comment by devarops** [comment]
Una alternativa es que agregues un `.gitignore` y en ese archivo incluyas `.*` para que se ignore a sí mismo. Eso resolvería tu problema sin la necesidad de consignar el `.gitignore`. ¿Qué opinan los demás?

**Comment by nepito** [comment]
Tradicionalmente así es como lo resolvemos. Agregando el `.gitignore` a nuestro repositorio local y no lo consignamos.

**Comment by devarops** [comment]
Así es como yo lo resolví, ¿pero tal vez es momento de que revisemos esa tradición?

**Comment by devarops** [comment]
@xwalls ¿Tú que opinas?

**Comment by xwalls** [comment]
personalmente creo que es buena práctica que el repo mismo tenga un .gitignore se agregue al repositorio.
por el momento lo solucionamos de la forma tradicional de geci, así que dado así el caso, estoy bien.

**Comment by devarops** [comment]
@xwalls  No creo que nadie del equipo se oponga a que agreges el `.gitignore`.
