### ISSUE TITLE
No hay documentacion en el archivo Tablanal.py

### ISSUE THREAD

**Issue by xwalls** [IslasGECI/metadata_tools#7]
Al no haber algun comentario para documentar dicha clase puede ser difícil la comprensión de su utilidad.

_Originally posted by @xwalls in https://github.com/IslasGECI/metadata_tools/issues/2#issuecomment-791034290_

**Comment by nepito** [comment]
@xwalls por favor se más propositivo en tus comentarios. Tal vez podrías agregar algún par de ejemplos de cómo lo intentaste usar. Agrega sugerencias.

**Comment by xwalls** [comment]
gracias nepo, será lo primero que haga. mañana

**Comment by xwalls** [comment]
ya revise que el archivo tablanal.py fue eliminado. por ahora este issue no tiene razón de ser.
