### ISSUE TITLE
Recomiendo refactorizar el nombre de las variables

### ISSUE THREAD

**Issue by xwalls** [IslasGECI/metadata_tools#8]
recomiendo refactorizar el nombre de las variables
`diccionario`
y
`Campo`

pueden no ser muy claras

_Originally posted by @xwalls in https://github.com/IslasGECI/metadata_tools/issues/2#issuecomment-791035698_

**Comment by nepito** [comment]
@xwalls por favor se más preciso en la descripción de tus recomendaciones y sugerencias. Da la información necesario para que cualquier miembro del equipo las pueda atender. Agrega liga a la línea a la que te refieres. 

Agrega una sugerencia de cuáles podrían ser las mejoras que propones.

Tal vez no sea una refactorizada sino solo un cambio en el nombre de la variable.

**Comment by devarops** [comment]
@xwalls ¿Qué le falta a este _issue_ para poder cerrarlo?

**Comment by xwalls** [comment]
de hecho este mismo issue ya esta resuelto para mi.
estuvimos haciendo consignaciones donde cambiamos algunos nombres que no eran lo mejor y algunas otras de inglés a espanol.
seguro habrá alguna más pero por ahora estoy bien
