### ISSUE TITLE
Inspección NR 🤠

### ISSUE THREAD

**Issue by nepito** [IslasGECI/metadata_tools#9]
Es posible utilizar decoradores para refactorizar las pruebas `test_Field_add_property` y `test_Field_modify_property` que tienen código repetido:
![image](https://user-images.githubusercontent.com/35377740/110074410-075a5a80-7d36-11eb-968a-718f42e9e9f3.png)

Tal vez un cambio podría ser:
``` python
def Field_methods_property(specific_method):
    def wrapper():
        name_property = "new_property"
        expected_value = specific_method(name_property)
        dict_field = Campo.get_dict()
        obtained_value = dict_field[name_property]
        assert expected_value == obtained_value
    return wrapper

@Field_methods_property
def test_Field_add_property(name_property):
    expected_value = 0
    Campo.add_property(name_property, expected_value)
    return expected_value
```

---
Aquí hay código repetido, tal vez podrías aplicar un decorador que revise que la variable de entrada sea de la clase esperda:
![image](https://user-images.githubusercontent.com/35377740/110075953-8781bf80-7d38-11eb-9622-624553f98930.png)

---
Estudio: 40 minutos
Preparación: 60 minutos

**Comment by nepito** [comment]
> Es posible utilizar decoradores para refactorizar las pruebas `test_Field_add_property` y `test_Field_modify_property` que tienen código repetido:
> ![image](https://user-images.githubusercontent.com/35377740/110074410-075a5a80-7d36-11eb-968a-718f42e9e9f3.png)
> 
> Tal vez un cambio podría ser:
> 
> ```python
> def Field_methods_property(specific_method):
>     def wrapper():
>         name_property = "new_property"
>         expected_value = specific_method(name_property)
>         dict_field = Campo.get_dict()
>         obtained_value = dict_field[name_property]
>         assert expected_value == obtained_value
>     return wrapper
> 
> @Field_methods_property
> def test_Field_add_property(name_property):
>     expected_value = 0
>     Campo.add_property(name_property, expected_value)
>     return expected_value
> ```
> 
> Aquí hay código repetido, tal vez podrías aplicar un decorador que revise que la variable de entrada sea de la clase esperda:
> ![image](https://user-images.githubusercontent.com/35377740/110075953-8781bf80-7d38-11eb-9622-624553f98930.png)
> 
> Estudio: 40 minutos
> Preparación: 60 minutos

Ya borramos estas pruebas, pues borramos la clase `Field`.

**Comment by devarops** [comment]
@nepito ¿Qué le falta a este _issue_ para poder cerrarlo?

**Comment by nepito** [comment]
Voy a cerrar el _issue_ y abrir uno nuevo cuando hagamos la siguiente inspección.

**Comment by devarops** [comment]
![Celebrate](https://i.giphy.com/media/35HTaxVJWzp2QOShct/giphy.webp)
